vo=gpu-next
hwdec=vaapi

hls-bitrate=max
prefetch-playlist=yes

sub-ass-override=force
sub-fonts-dir='~/.config/mpv/fonts'
sub-font='Open Sans'
sub-font-size=42
sub-color="#FFFFFF"
sub-border-size=2.5
sub-border-color="#000000"
sub-shadow-offset=1
sub-shadow-color="#000000"

audio-file-auto=fuzzy
sub-auto=fuzzy
